# SGE_BLOC2

# Verificación de la conexión a la base de datos

La siguiente imagen muestra la ejecución del script `connect.py`, donde se intenta conectar a una base de datos PostgreSQL llamada `the_bear`. 

Si la conexión es exitosa, se imprime el objeto de conexión. Si falla, se muestra un mensaje de error indicando el problema.

![Captura de la conexión]![baixa](https://github.com/user-attachments/assets/f558413f-285c-40c6-b873-fc33aafd0b17)



![image](https://github.com/user-attachments/assets/20eb8644-9a1d-45bf-b2e5-c8b790aa86d2)

